<?php

include('class/prepare.inc.php');
include('class/log.inc.php');
$log = new Log();
include('class/page.inc.php');
$html_page = new Page();
include('class/auth.inc.php');
include('class/user.inc.php');
include('class/group.inc.php');
include('class/clan.inc.php');
include('class/trust.inc.php');
include('class/hint.inc.php');
include('class/league.inc.php');
include('class/menu.inc.php');
 $menu = new Menu($gamesmenu);
 $commmenu = new Menu($commmenu);
 $external_menu = new Menu($external_menu);
include('class/box.inc.php');
include('class/email.inc.php');
include('class/pm.inc.php');
include('class/forum.inc.php');
include('class/errorbox.inc.php');
include('class/notification.inc.php');
include('class/logbox.inc.php');
include('class/chat.inc.php');
include('class/loginbox.inc.php');
 $loginbox = new LoginBox($langs, $_SESSION['_lang']);
include('class/ss_box.inc.php');
 $ssbox = new SSBox($langs, $_SESSION['_lang']);
include('class/newsbox.inc.php');
 $newsbox = new NewsBox($langs, $_SESSION['_lang']);
include('class/videobox.inc.php');
 $videobox = new VideoBox($langs, $_SESSION['_lang']);
include('class/announcementbox.inc.php');
 $announcementbox = new AnnouncementBox($langs, $_SESSION['_lang']);
include('class/pagingbox.inc.php');
 $pagingbox = new PagingBox($langs, $_SESSION['_lang']);
include('class/pagebox.inc.php');
 $pagebox = new PageBox($langs, $_SESSION['_lang']);
include('class/forumbox.inc.php');
 $forumbox = new ForumBox($langs, $_SESSION['_lang']);
include('class/wager_log.inc.php');
include('class/manager_log.inc.php');
include('class/rvs_manager_log.inc.php');
include('class/bracket_log.inc.php');
include('class/bracket_users_log.inc.php');
include('class/wager_users_log.inc.php');
include('class/manager_users_log.inc.php');
include('class/rvs_manager_users_log.inc.php');
include('class/solo_manager_log.inc.php');
include('class/solo_manager_users_log.inc.php');
include('class/manager_tournament_log.inc.php');
include('class/clan_log.inc.php');
include('class/clan_users_log.inc.php');
include('class/managerbox.inc.php');
 $managerbox = new ManagerBox($langs, $_SESSION["_lang"]);
include('class/wagerbox.inc.php');
 $wagerbox = new WagerBox($langs, $_SESSION["_lang"]);
include('class/bracketbox.inc.php');
 $bracketbox = new BracketBox($langs, $_SESSION["_lang"]);
include('class/donationbox.inc.php');
 $donationbox = new DonationBox($langs, $_SESSION['_lang']);
include('class/networkbox.inc.php');
 $networkbox = new NetworkBox($langs, $_SESSION['_lang']);
include('class/surveybox.inc.php');
 $surveybox = new SurveyBox($langs, $_SESSION['_lang']);
include('class/shopbox.inc.php');
 $shopbox = new ShopBox($langs, $_SESSION['_lang']);
include('class/supporterbox.inc.php');
 $supporterbox = new SupporterBox($langs, $_SESSION['_lang']);
include('class/shortcutsbox.inc.php');
 $shortcutsbox = new ShortcutsBox($langs, $_SESSION['_lang']);
include('class/clubbox.inc.php');
 $clubbox = new ClubBox($langs, $_SESSION['_lang']);
include('class/clanbox.inc.php');
 $clanbox = new ClanBox($langs, $_SESSION['_lang']);
include('class/ratingbox.inc.php');
 $ratingbox = new RatingBox($langs, $_SESSION['_lang']);
include('class/countdownbox.inc.php');
$countdownbox = new CountdownBox($langs, $_SESSION['_lang']);
include('class/timelinebox.inc.php');
 $timelinebox = new TimelineBox($langs, $_SESSION['_lang']);
include('class/basket_item.inc.php');
include('class/basket.inc.php');
include('class/basketbox.inc.php');

include('class/credits.inc.php');
include('class/credits_log.inc.php');
include('smarty/libs/Smarty.class.php');
 $smarty = new Smarty;
 //$smarty->debugging = true;
 $smarty->registerPlugin("function","translate", "get_translation");

?>